name: 'CODEOWNERS action'
description: 'Extracts CODEOWNERS information'
author: 'Sebass van Boxel'
inputs:
  path:
    required: false
    description: 'Location of codeowners file'
    default: './CODEOWNERS'
output: 
  codeowners:
    description: "JSON string containing all CODEOWNER information"
runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'user-check'  
  color: 'gray-dark'
