name: 'CODEOWNERS action'
description: 'Extracts CODEOWNERS information'
author: 'Sebass van Boxel'
inputs:
  path:
    required: false
    description: 'Location of codeowners file'
    default: './CODEOWNERS'
  file_match_info:
    required: false
    description: Output how version controlled files match CODEOWNERS rules
    default: 'false'
  include_no_owners:
    required: false
    description: If files without owners should be included or not
    default: 'false'
output:
  codeowners:
    description: "JSON string containing all CODEOWNERS information"
  filematches:
    description: "JSON string contain how files match CODEOWNERS rules"
runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'user-check'  
  color: 'gray-dark'
